name: FnOScanner
options:
  bundleIdPrefix: com.mohit
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  FnOScanner:
    type: application
    platform: macOS
    sources:
      - path: FnOScanner
        excludes:
          - "*.entitlements"
          - "Info.plist"
    info:
      path: FnOScanner/Info.plist
      properties:
        CFBundleDisplayName: "FnO Scanner"
        CFBundleName: "FnO Scanner"
        LSApplicationCategoryType: "public.app-category.finance"
        CFBundleURLTypes:
          - CFBundleURLName: "Kite Callback"
            CFBundleURLSchemes:
              - fnoscanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mohit.fno-scanner
        PRODUCT_NAME: FnO Scanner
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: FnOScanner/FnOScanner.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
    entitlements:
      path: FnOScanner/FnOScanner.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
